version: '3.8'

services:
  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: weather_app
    ports:
      - "8001:8001"
    env_file:
      - ../.env
    depends_on:
      - minio
      - dynamodb
    volumes:
      - ../app:/app

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - ../.env
    command: server /data --address ":9000" --console-address ":9001"
    volumes:
      - minio_data:/data

  dynamodb:
    image: amazon/dynamodb-local
    container_name: dynamodb
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb"
    volumes:
      - dynamodb_data:/home/dynamodblocal/data

volumes:
  minio_data:
  dynamodb_data: